src/types.rs

serum & raydium use deprecated commitment names

feat: add support for legacy commitment names

---

src/accounts.rs
src/main.rs
src/metrics.rs
src/rpc.rs

feat: add pubsub metrics

---

src/rpc.rs

In case of too many requests from backend, it's possible another thread was more lucky to get through. It's cheap to check, so do it.

feat: check cache if received error

---

src/rpc.rs

In case of too many requests from backend, it's possible another thread was more lucky to get through. It's cheap to check, so do it.
(It's #9 again)

Check cache if error received

---

src/accounts.rs
src/metrics.rs
src/rpc.rs

Add backend errors and pubsub command metrics

Improve metrics

---

Cargo.toml
src/accounts.rs
src/rpc.rs

Implement backoff

---

src/accounts.rs
src/rpc.rs
src/types.rs

Allow caching getProgramAccounts with dataSize filter, which is popular with some apps (i.e. raydium).

Cache datasize filter

---

src/accounts.rs
src/rpc.rs
src/types.rs

https://github.com/zubr-exchange/cacherpc/issues/6

DRAFT: feat: support all filters

---

Cargo.toml
src/main.rs

* file is reopened on SIGHUP
* while there, make logging non-blocking

feat: add `--log-file` option to log to file

---

src/accounts.rs

Fixes premature purging of cached keys

fix: fix stupid typo in purge code

---

src/accounts.rs
src/main.rs
src/rpc.rs
src/types.rs

- send websocket pings and disconnect if timeout elapsed
- skip checking for cache if we're disconnected

feat: better track websocket disconnection/timeout

---

src/accounts.rs
src/metrics.rs
src/rpc.rs
src/types.rs

* add support for fragmented websocket frames (useful for large accounts)
* add ping/pong dance to check websocket liveness
* add more metrics (as always)

Websocket improvements

---

src/accounts.rs
src/main.rs
src/rpc.rs
src/types.rs

Add support for multiple websocket connections for different accounts. Reduces losing cache in case websocket connection is lost.

Support multiple websocket connections

---

src/rpc.rs
src/types.rs

Stop lying about which slot we have received.

Use real update slot

---

src/rpc.rs

Validator ignores invalid commitments and defaults to None.

Ignore invalid commitments 

---

src/accounts.rs
src/metrics.rs

add actor_id field everywhere + hide verbose filtered out

Better logging

---

src/accounts.rs

WriteHandler::finished isn't always called, leading to half-disconnected state.

fix: close everything at once

---

Cargo.toml

Seems to work a little better with validator shutdown

awc connection pool workaround

---

src/rpc.rs

Fixes panic on empty params list in `getAccountInfo`

refactor: move out parameters parsing into a separate function

---

src/accounts.rs
src/types.rs

Make dbs account for their entries metrics

fix: db entries metrics

---

src/accounts.rs
src/rpc.rs
src/types.rs

feat: support withContext toggle in getProgramAccounts

---

src/rpc.rs

Fixes https://github.com/zubr-exchange/cacherpc/issues/48#issuecomment-918824369

fix: allow null for withContext

---

Cargo.toml
src/main.rs
src/rpc.rs

Example config 
```
[rpc.request_limits]
account_info = 5
program_accounts = 1
```

feat: load config from file

---

src/main.rs

Fixes https://github.com/zubr-exchange/cacherpc/issues/118

fix: allow anything after application/json

---

src/rpc.rs

It was done in order to ensure that all requests ragardless of the type
will be subjected to check by WAF rules

Moved WAF filtering to rpc handler

---

src/pubsub.rs
src/rpc.rs

For a given subscription and commitment level, if a cache entry is
found, and web socket connection is estabilished, then check whether we
have a corresponding active websocket subscription for that
subscription+commitment pair
Closes #152

Modified web socket subscription check for given cache entry

---

src/rpc.rs

Now batch requests will be iterated by their subqueries and for each
subquery WAF evaluation will be performed, if all elements pass the
check, request will be handled further, otherwise, WAF rejection error
will be returned to client
Closes #197

Added WAF support for batch requests

---

Cargo.lock
Cargo.toml
src/metrics.rs
src/pubsub.rs
src/rpc.rs

This reverts commit 86a99d959a6b1dcdc215bb0a3db987f835b03a81.

Revert "Added logic to deduplicate subscriptions (#185)"

---

src/metrics.rs
src/rpc.rs

Request types: getAccountInfo, getProgramAccounts, passthrough

Added new metric for counting requests of each type

---

src/types.rs

Currently observed filter groups for an account are book-keeped by account key, which is a bug since account can have different states for different commitments hence filter groups that matches the account state are not necessarily the same for all commitments.

fix: index observed filters by key and commitment

---

Cargo.lock
Cargo.toml
src/cli.rs
src/control.rs
src/main.rs
src/rpc/cacheable.rs
src/rpc/state.rs

User's can now switch the wide-filters prefetch based optimization on and off via control interface

Made wide filters based gpa requests optional
